Whitelisting via tab analysis for chromium
younesaassila/ttv-lol-pro pull request #256
Opened 2023-09-24 11:39 UTC by lukefanning

After noticing that whitelisting only worked on Firefox, I really wanted the same feature for Chrome.

Ran into the insurmountable issue of being limited by Chrome's proxy security and the proxy auto-config script.

So I decided to come up with a compromised solution that involves basing whether to enable proxying based on the twitch tabs you have open. If you only have whitelisted tabs open then the proxy will not be enabled but if even one tab is open that isn't whitelisted then the proxy will be enabled.

Feels free to close this PR if this isn't a suitable solution for you guys :)

2023-09-24 11:44 UTC, younesaassila commented
This seems like a good compromise. I'll look more into it once I have a bit more time to work on this project. In the meantime, could you run `npm run lint:fix` to fix linter errors? Thanks :)

2023-09-26 10:31 UTC, younesaassila requested changes
I've reviewed the code and found some things to change, please fix them so I can merge this PR :)

2023-09-26 10:31 UTC, younesaassila commented on src/background/handlers/onTabCreated.ts
> +      var isNonWhitelistedChannel = true;
Please change `var` to `let`

2023-09-26 10:31 UTC, younesaassila commented on src/background/handlers/onTabCreated.ts
> +      if (url.pathname && url.pathname.length > 0) {
Please use the `twitchChannelNameRegex` regex to get the channel name from the URL (in `src/common/ts/regexes.ts`)

2023-09-26 10:31 UTC, younesaassila commented on src/background/handlers/onTabRemoved.ts
> +              return isChannelWhitelisted(url.pathname.substring(1));
Same remark as above (use the `twitchChannelNameRegex` regex instead)

2023-09-26 10:31 UTC, younesaassila commented on src/background/handlers/onTabRemoved.ts
> +      ).then(res => {
Consider making this function asynchronous and using `await` syntax instead of `.then()` with a better variable name like `tabToWhitelistStatus` perhaps?

2023-09-26 10:31 UTC, younesaassila commented on src/background/handlers/onTabUpdated.ts
> +      if (urlObj.pathname && urlObj.pathname.length > 0) {
Again here for the `twitchChannelNameRegex` regex

2023-09-26 10:31 UTC, younesaassila commented on src/background/handlers/onTabUpdated.ts
> +      var isNonWhitelistedPage = true;
`var` -> `let`
Since this seems to be the same code as above, consider putting that code in a function in `src/common` like `isTwitchTabWhitelisted`

2023-10-04 15:37 UTC, younesaassila commented
I checked out your PR in a branch on this repo, fixed the few issues I found, and merged into the v2.2.0 branch. Thanks for your contribution :)

2023-10-04 15:37 UTC, closed without merging

2023-10-05 19:26 UTC, zGato commented
@lukefanning Please DM me on Discord if you want to get the donators proxies. Thank you for your contribution ❤️ 
`zgato_`